featureClass:
    firstorder: ['10Percentile', '90Percentile', 'Energy', 'Entropy',
                 'InterquartileRange', 'Kurtosis', 'Maximum', 'MeanAbsoluteDeviation',
                 'Mean', 'Median', 'Minimum', 'Range', 'RobustMeanAbsoluteDeviation',
                 'RootMeanSquared', 'Skewness', 'Uniformity', 'Variance']
    #shape2D: [] # Shape features are omitted.
    glcm: []
    glrlm: []
    glszm: []
    ngtdm: []
    gldm: []